database:
  type: SQLITE
  sqlite:
    file: data/marriages.db
  mysql:
    host: 127.0.0.1
    port: 3306
    database: josfamily
    username: root
    password: change-me
    parameters: useSSL=false&cachePrepStmts=true&prepStmtCacheSize=250&prepStmtCacheSqlLimit=2048
  pool:
    maximum-pool-size: 8
    connection-timeout-ms: 10000

modules:
  proposal-distance:
    enabled: true
    radius: 8.0
  marriage-cost:
    enabled: true
    amount: 300.0
    charge-mode: BOTH
    # ACCEPT & SEND ARE THE ONLY VALID VALUES
    # ACCEPT: The player will be charged when they accept the proposal
    # SEND: The player will be charged when they send the proposal
    proposer-charge-stage: SEND
    target-charge-stage: ACCEPT
  marriage-ring:
    enabled: true
    cost: 500.0
    material: GOLD_NUGGET
    enchanted-glint: true

marriage:
  proposal-expiry-seconds: 60
  broadcast-marriages: true
  divorce-requires-confirmation: true
